### ISSUE TITLE
Add Some Functionality || Enhance ( UI ) User Interface / (UX) User Experience 

### ISSUE THREAD

**Issue by Shubhamjain287** [Shubhamjain287/Web-Devlopment-Projects#2]
Add Something Good to it or Enhance UI of the Website [List of Contributors](https://web-devlopment-projects-9dfjes81b-shubhamjain287.vercel.app/)

![Screenshot (22)](https://user-images.githubusercontent.com/85169074/195686265-2e304b17-bbd2-4537-b190-667ea011a1dd.png)

**Comment by zachyo** [comment]
No specificity but I can add some functionality and improve the UI

**Comment by Shubhamjain287** [comment]
> No specificity but I can add some functionality and improve the UI

Ohk This issue is Assigned to You , so you can start working on it by adding some functionality and improving the UI ...!
And You Can also add Your Web Development Projects in `Web Development` Folder for others to see !!
