### ISSUE TITLE
Add Your Web Development Projects

### ISSUE THREAD

**Issue by Shubhamjain287** [Shubhamjain287/Web-Devlopment-Projects#3]
Adding Your Simple Web Development Projects will Allow You to Contribute in this Repository. Include Your Web Development Projects in the `Web Development Folder` so others can see your contribution and interact with it !!

You Can also add Your Name in [List of Contributors](https://web-devlopment-projects-9dfjes81b-shubhamjain287.vercel.app/) by Adding Your Name and Details in `public/userdata` file !!

**Comment by vilasrhegde** [comment]
@Shubhamjain287 Can you assign me this?

**Comment by yogesh-9999** [comment]
!assign

**Comment by Uttkarrsh** [comment]
Should I create an issue then create a PR for that issue?

**Comment by Shubhamjain287** [comment]
> Should I create an issue then create a PR for that issue?

Create a PR Directly !!

**Comment by Shubhamjain287** [comment]
> !assign

Ohk You Can Start Working on it !!

**Comment by Shubhamjain287** [comment]
> @Shubhamjain287 Can you assign me this?

ohk i'm Assigning You , You can start working now !!

**Comment by darkbits018** [comment]
@Shubhamjain287 can I contribute a landing page ??
If so please assign it to me
